environment:
  deploy_password:

shallow_clone: true

before_build:

build_script:
  - build.cmd runtests

test: off

test_script:
  #- nuget restore tests\Tests.sln
  #- test.cmd
  
deploy_script:
  #- deploy.cmd